USE [mj150206]
GO

/****** Object:  Table [dbo].[Line]    Script Date: 6/13/2020 10:00:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Line](
	[idLine] [dbo].[id] IDENTITY(1,1) NOT NULL,
	[Distance] [int] NULL,
	[CityFrom] [dbo].[id] NOT NULL,
	[CityTo] [dbo].[id] NOT NULL,
 CONSTRAINT [XPKLine] PRIMARY KEY CLUSTERED 
(
	[idLine] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [XAK1LineCities] UNIQUE NONCLUSTERED 
(
	[CityFrom] ASC,
	[CityTo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Line]  WITH NOCHECK ADD  CONSTRAINT [R_4] FOREIGN KEY([CityFrom])
REFERENCES [dbo].[City] ([idCity])
GO

ALTER TABLE [dbo].[Line] CHECK CONSTRAINT [R_4]
GO

ALTER TABLE [dbo].[Line]  WITH NOCHECK ADD  CONSTRAINT [R_5] FOREIGN KEY([CityTo])
REFERENCES [dbo].[City] ([idCity])
GO

ALTER TABLE [dbo].[Line] CHECK CONSTRAINT [R_5]
GO


