USE [mj150206]
GO

/****** Object:  Table [dbo].[Item]    Script Date: 6/13/2020 10:00:09 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Item](
	[Count] [int] NULL,
	[idArticle] [dbo].[id] NOT NULL,
	[idOrder] [dbo].[id] NOT NULL,
	[idItem] [dbo].[id] IDENTITY(1,1) NOT NULL,
	[Path] [dbo].[TextField] NULL,
 CONSTRAINT [XPKItem] PRIMARY KEY CLUSTERED 
(
	[idItem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [XAK1Item] UNIQUE NONCLUSTERED 
(
	[idOrder] ASC,
	[idArticle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Item]  WITH NOCHECK ADD  CONSTRAINT [R_8] FOREIGN KEY([idArticle])
REFERENCES [dbo].[Article] ([idArticle])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[Item] CHECK CONSTRAINT [R_8]
GO

ALTER TABLE [dbo].[Item]  WITH NOCHECK ADD  CONSTRAINT [R_9] FOREIGN KEY([idOrder])
REFERENCES [dbo].[Order] ([idOrder])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[Item] CHECK CONSTRAINT [R_9]
GO


