USE [mj150206]
GO

/****** Object:  Table [dbo].[Shop]    Script Date: 6/13/2020 10:03:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Shop](
	[idShop] [dbo].[id] IDENTITY(1,1) NOT NULL,
	[Name] [dbo].[TextField] NULL,
	[Discount] [int] NULL,
	[idCity] [dbo].[id] NOT NULL,
 CONSTRAINT [XPKShop] PRIMARY KEY CLUSTERED 
(
	[idShop] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [XAK1ShopName] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Shop] ADD  CONSTRAINT [Shop_Discount_Default_609840236]  DEFAULT ((0)) FOR [Discount]
GO

ALTER TABLE [dbo].[Shop]  WITH NOCHECK ADD  CONSTRAINT [R_2] FOREIGN KEY([idCity])
REFERENCES [dbo].[City] ([idCity])
GO

ALTER TABLE [dbo].[Shop] CHECK CONSTRAINT [R_2]
GO


